### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sailfish009**
tested on vue.js, works fine for me.

### CODE REVIEW

**Comment by dankogai** [comment]
It can even be just `import * as $C from 'js-combinatorics'` once `npm install js-combinatorics` is done.  Or `import * as $C from 'https://cdn.jsdelivr.net/npm/js-combinatorics@1.4.5/combinatorics.min.js';` as in the **USAGE** section.  Where you import it from is up to the user.  I consider the current `./combinatorics.js` better than your suggestion.

**Comment by sailfish009** [comment]
"./combinatorics.js" not works for me. 

`yarn add js-combinatorics `

**Comment by dankogai** [comment]
"does not work for me" is not good enough a reason.  as I said where you import from is up to your environment. There is no way to make it work for 100% of the cases.  Case dismissed.

**Comment by sailfish009** [comment]
fair enough, i will keep my README.md, BTW, Thanks for this library!

**Pull request closed without merging**
